# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Kj-X4ffGxX-uJRfiRTryofDLhb1rnyfx

# 02-5 ditionary
"""

# 딕셔너리 : Key와 Value를 한 쌍으로 가지는 자료형
# 특징 : 리스트나 튜플처럼 순차적으로 해당 요솟값을 구하지 않고, Key를 통해 Value를 얻는다.

# 딕셔너리의 기본 모습
# {Key1 : Value1, Key2 : Value2, Key3 : Value3}
dic = {'name':'pey','phone':'010-9999-1234','birth':'1118'}

# Key로 정숫값 1, Value로 문자열 'hi'를 사용한 예
a = { 1: 'hi'}

# Value에 리스트 넣기
a = {'a':[1,2,3]}

"""# 딕셔너리 쌍 추가, 삭제하기"""

# 딕셔너리 쌍 추가하기
a = { 1:'a'}
a[2] = 'b'
a

a['name']='pey'
a

a[3]=[1,2,3]
a

# 딕셔너리 요소 삭제하기
a = {1: 'a', 2: 'b', 'name': 'pey', 3: [1, 2, 3]}
del a[1]
a

"""# 딕셔너리 사용하는 방법

"""

# 딕셔너리에서 Key를 사용해 Value 얻기
grade = {'pey':10,'julliet':99}
grade['pey']

grade = {'pey':10,'julliet':99}
grade['julliet']

a = {1:'a',2:'b'}
a[1]
a[2]
# Key가 2인 요소인 Value를 반환함

a = {'a':1,'b':2}
a['a']

a = {'a':1,'b':2}
a['b']

# Key를 사용해서 Value를 얻는 방법
dic = {'name':'pey','phone':'010-9999-1234','birth':1118}
dic['name']

dic = {'name':'pey','phone':'010-9999-1234','birth':1118}
dic['phone']

dic = {'name':'pey','phone':'010-9999-1234','birth':1118}
dic['birth']

"""# 딕셔너리 만들 때 주의할 사항"""

# Key는 고유한 값이므로 중복되는 Key 값을 설정해 놓으면 하나를 제외한 나머지 것들이 모두 무시된다는 점
a = {1:'a',1:'b'}
a

# 딕셔너리에는 동일한 Key가 중복으로 존재할 수 없다.
# Key에 리스트는 쓸 수 없다.
# 튜플은 Key로 쓸 수 있다.
# 단, Value에는 변하는 값이든, 변하지 않는 값이든 아무 값이나 넣을 수 있다.

"""# 딕셔너리 관련 함수"""

# Key 리스트 만들기-keys
a = {'name':'pey','phone':'010-9999-1234','birth':1118}
a.keys()

# 리스트를 사용하는 것과 별 차이는 없지만 고유의 함수는 수행할 수 없다.
for k in a.keys() :
  print(k)
# print(k)를 입력할 때 들여쓰기를 하지 않으면 오류 발생함

# dic_keys 객체를 리스트로 변환
list(a.keys())

# Value 리스트 만들기-values
a.values()

# Key, Value 쌍 얻기-items
a.items()
# items 함수는 Key와 Value의 쌍을 튜플로 묶은 값을 객체로 리턴함

# Key: Value 쌍 모두 지우기-clear
a.clear()
a
# clear 함수는 딕셔너리 안의 모든 요소 삭제함

# Key로 Value 얻기-get
a = {'name':'pey','phone':'010-9999-1234','birth':1118}
a.get('name')

a = {'name':'pey','phone':'010-9999-1234','birth':1118}
a.get('phone')

# 딕셔너리 안에 찾으려는 Key가 없을 경우,
# 미리 정해 둔 디폴트 값을 대신 가져오게 하고 싶을 때
# get을 사용하면 편리함
a.get('nokey','foo')

# 해당 Key가 딕셔너리 안에 있는지 조사하기-in
a = {'name':'pey','phone':'010-9999-1234','birth':1118}
'name' in a

# 1분 코딩
a = {'name':'홍길동','brith':1128,'age':30}