# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XQNexxrW1wsrOHYcCIhCNfR07t2gf9oM

# 02-07 불 자료형
"""

# 불 자료형이란 참과 거짓을 나타내는 자료형
# 2가지 값만을 가질 수 있음(True, False)

"""# 불 자료형 어떻게 사용할까?"""

a=True
b=False

type(a)

type(b)

# 불 자료형은 조건문의 리턴값으로도 사용됨
1==1
# 1==1은 '1과 1이 같은가?'를 묻는 조건문

2>1

2<1

"""# 자료형과 참과 거짓"""

# 문자열, 리스트, 튜플, 딕셔너리 등의 값이 비어있으면 거짓이 되고, 비어 있지 않으면 참이 된다.
# 숫자에서는 0일 때 거짓이 된다.

a = [1,2,3,4]
while a : # a가 참인 동안
  print(a.pop()) # 리스트의 마지막 요소를 하나씩 꺼낸다.

if [] : # 만약 []가 참이면
  print("참") # '참'문자열 출력
else: # 만약 []가 거짓이면
  print("거짓") # '거짓'문자열 출력

if [1,2,3]:
  print("참")
else:
  print("거짓")
# 만약 [1,2,3]이 참이면 "참"이라는 문자열을 출력하고, 그렇지 않으면 "거짓"이라는 문자열을 출력하라

"""# 불 연산"""

bool('python')

bool('')

bool([1,2,3])

bool([])

bool(0)

bool(3)