# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nKxShnCCDqGHSsKWGbeSSVgmeQkmBvvP

# 02-08 자료형의 값을 저장하는 공간, 변수
"""

# 변수를 만들 때는 =(assignment) 기호를 사용한다.
# 변수_이름 = 변수에_저장할_값
# 변수란 : 객체를 가리키는 것, 데이터(값)와 같은 것 의미함
a=[1.2,3]

a=[1,2,3]
id(a)

"""# 리스트를 복사하고자 할 때"""

a = [1,2,3]
b=a
a is b # a와 b가 가리키는 객체가 같을까?

a[1]=4
a

# [:]이용하기
a=[1,2,3]
b=a[:] # 리스트 a의 처음 요소부터 끝 요소까지 슬라이싱
a[1]=4
a

# copy 모듈 이용하기
from copy import copy # copy 모듈에 있는 copy 함수 import
a=[1,2,3]
b=copy(a)
b is a

a = [1,2,3]
b=a.copy()
b is a

"""# 변수를 만드는 여러 가지 방법"""

# 튜플로 a,b에 값 대입
a,b=('python','Life')
(a,b)='python','Life'

# 리스트로 변수 만들기
[a,b]=['python','Life']

# 여러 개의 변수에 같은 값 대입
a=b='python'

# 두 변수의 값을 간단히 바꾸기
a=3
b=5
a,b = b,a # a와 b의 값을 바꿈
a

a = [1,2,3]
b = [1,2,3]
a is b