# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N_J_ffzRiPfapa2l88w65aJWZniVDw_6

# 02-06 집합 자료형
"""

s1 = set([1,2,3])
s1

s2 = set("Hello")
s2

"""# 집합 자료형의 특징"""

# 중복을 허용하지 않는다.(데이터의 중복 제거위한 필터로도 사용됨)
# 순서가 없다
# 인덱싱을 통해 요솟값을 얻을 수 없다.
# set 자료형에 저장된 값을 인덱싱으로 접근하려면 리스트나 튜플로 변환후에 해야한다

s1 = set([1,2,3])
l1 = list(s1)
l1

l1[0]

t1= tuple(s1)
t1

t1[0]

"""# 교집합, 합집합, 차집합 구하기"""

s1=set([1,2,3,4,5,6])
s2=set([4,5,6,7,8,9])

# 교집합 구하기
s1=set([1,2,3,4,5,6])
s2=set([4,5,6,7,8,9])
s1 & s2

s1=set([1,2,3,4,5,6])
s2=set([4,5,6,7,8,9])
s1.intersection(s2)

# 합집합 구하기
# 중복해서 포함된 값은 1개씩만 표현됨
s1|s2

# union 함수를 사용해도 됨
s1.union(s2)

s2.union(s1)

# 차집합 구하기
s1 - s2

s2 - s1

# difference 함수 사용해도 됨
s1.difference(s2)

s2.difference(s1)

"""# 집합 자료형 관련 함수"""

# 값 1개 추가하기-add
s1=set([1,2,3])
s1.add(4)
s1

# 값 여러 개 추가하기-update
s1=set([1,2,3])
s1.update([4,5,6])
s1

# 특정 값 제거하기-remove
s1=set([1,2,3])
s1.remove(2)
s1