# -*- coding: utf-8 -*-
"""Colab 시작하기

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb

# 되새김문제
"""

# 01 평균 점수 구하기
(80+75+55)/3

# 02 홀수, 짝수 판별하기
13%2

# 03 주민등록번호 나누기
pin="881120-1068234"
yyyymmdd = pin[:6]
num = pin[7:]
print(yyyymmdd)
print(num)

# 04 주민등록번호 인덱싱
pin = "881120-1068234"
print(pin[7:8])

# 05 문자열 바꾸기
a="a:b:c:d"
b=a.replace(":","#")
print(b)

# 06 리스트 역순 정렬하기
a=[1,3,5,4,2]
a.sort()
a.reverse()
print(a)

# 07 리스트를 문자열로 만들기
a=['Life','is','too','short']
result=" ".join(a)
print(result)

# 08 튜플 더하기
a=(1,2,3)
a= a+(4,)
print(a)

# 09 딕셔너리 키
a=dict()
a[('a',)]='python'
a[250]='python'
a

# 10 딕셔너리 값 추출하기
a={'A':90,'B':80,'C':70}
result=a.pop('B')
print(a)
print(result)

# 11 리스트에서 중복 제거하기
a=[1,1,1,2,2,3,3,3,4,4,5]
aSet=set([1,1,1,2,2,3,3,3,4,4,5])
b=list(aSet)
print(b)

# 12 파이썬 변수
a=b=[1,2,3]
a[1]=4
print(b)