# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BALoikuRxp0MRCGzsTkeGMgHLM8aDwma

# 03-03 for문
"""

# for문의 기본 구조
# for 변수 in 리스트(또는 튜플, 문자열) :
#   수행할_문장 1
#   수행할_문장 2

# 전형적인 for문
test_list=['one','two','three']
for i in test_list : # one,two,three를 순서대로 i에 대입
  print(i)

# 다양한 for문의 사용
a=[(1,2),(3,4),(5,6)]
for(frist, last) in a :
  print(frist+last)

# for문의 응용
marks=[90,25,67,45,80]
number=0
for mark in marks :
  number=number+1
  if mark >= 60 :
      print("%d번 학생은 합격입니다." % number)
  else :
      print("%d번 학생은 불합격입니다." % number)

# for문과 continue문
# for문 안의 문장을 수행하는 도중 continue문을 만나면 for문의 처음으로 돌아가게 된다
marks=[90,25,67,45,80]
number=0
for mark in marks :
  number=number+1
  if mark < 60 :
      continue
  print("%d번 학생 축하합니다. 합격입니다." % number)

# for문과 함께 자주 사용하는 range함수
a=range(10)
a

# 시작 숫자와 끝 숫자를 지정하려면 range(시작_숫자,끝_숫자) 형태를 사용하는데, 이때 끝숫자는 포함되지 않는다.
a=range(0,11)
a

# range함수의 예시 살펴보기
add=0
for i in range(1,11):
  add = add+i
print(add)

marks=[90,25,67,45,80]
for number in range(len(marks)) :
  if marks[number] < 60 :
      continue # 점수가 60점 미만이면 맨 처음으로 돌아간다.
  print("%d번 학생 축하합니다. 합격입니다." % (number+1))

# for문과 range함수를 사용하여 1부터 100까지 더해 보자.
a=0
for i in range(1,101):
  a += i
print(a)

# for와 range를 이용한 구구단
for i in range(2,10):
    for j in range(1,10):
        print(i*j,end=" ")
    print('')

# 리스트 컴프리헨션 사용하기
a=[1,2,3,4]
result=[]
for num in a :
  result.append(num*3)
print(result)

# 바로 위 코딩을 간단하게
a=[1,2,3,4]
result=[num*3 for num in a]
print(result)

# 바로 위 코딩에서 [1,2,3,4] 중에서 짝수에만 3을 곱하여 담고 싶다면
a=[1,2,3,4]
result=[num*3 for num in a if num%2 == 0]
print(result)

# 리스트 컴프리헨션 문법
# [표현식 for 항목 in 반복_가능_객체 if 조건문]

# for문을 2개 이상 사용할 때의 문법
# [표현식 for 항목1 in 반복_가능_객체1 if 조건문1
#         for 항목n in 반복_가능_객체n if 조건문n]